### ISSUE TITLE
An issue with token conversion

### ISSUE THREAD

**Issue by Blue-Shadow** [Kyle873/DoomRPG#10]
Let's say you have enough credits to do two individual token conversions (or more). Doing the first conversion works fine. However, if you try and do the second conversion without leaving the interface/menu, you don't get what you paid for. Here is my case:

I have 6 stat, 4 stat cap and 18 skill tokens. I have nearly 60,000 credits, enough for two "1 stat cap token -> 10 stat tokens" conversions, as it costs 25,000 credits per conversion. I choose my option and tell it to convert. Now I have 16 stat and 3 stat cap tokens, and lost 25,000 credits -- everything is good so far. If I tell it to convert again (as I mentioned above, without leaving the menu), An "error" sound will be played, I will lose 5 stat tokens and gain 1 skill token, and will lose 25,000 credits.

**Comment by Kyle873** [comment]
Token Converter has been rewritten and works differently now, so this is no longer valid.
