### ISSUE TITLE
Outpost Shield Recharger is recharging a non-existant shield

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#15]
Started a new game with the latest build, and headed to the outpost because E1M1 has tactical nuke.

My bad luck aside, I went a few rounds in the arena, then went to the recharging stations. I ended up losing credits on the shield recharger, which went through the motions of recharging my shield. Except that I didn't have a shield anything at all.

**Comment by Kyle873** [comment]
Should be fixed now.
