### ISSUE TITLE
Shop is now Locker(non-issue)

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#16]
With Shop Anywhere turned off, the shop at the UAC Outpost appears to just bring up the locker when I try to interact with the shopkeeper marine.

**Comment by Kyle873** [comment]
... Did you try pressing the mode swap key?

**Comment by Silentdarkness12** [comment]
....That's a thing?

Damnit, fine print. *sigh* nevermind!
