### ISSUE TITLE
Old credit graphics?

### ISSUE THREAD

**Issue by iSpook** [Kyle873/DoomRPG#18]
Could there be, in some far off point in the future, that a cvar could be made so that Credits use the Old sprites? The new ones look fine and all, but I liked the Brightly-colored sprites you were using a while back ago.

**Comment by Kyle873** [comment]
That can't be done with a CVAR, unfortunately.

**Comment by Silentdarkness12** [comment]
Actually, I think that could be done with CVAR and some ACS.

CVAR to trigger it, and upon loading up the Outpost, do a check on that CVAR via script. If it decides it's time for the old credit sprites, then use ACS to change the credit sprite linedef textures accordingly.

I mean, that'd require reloading the map, but there's a way it's doable.

Here's an example:

[CVARINFO]
user bool UseOldCredits = false;
[CVARINFO END]

Script "OldCreditCheck" ENTER
{
if(GetCvar("UseOldCredits")==false)
{
Terminate;
}
else
{
SetLineTexture(504,SIDE_FRONT,TEXTURE_MIDDLE,"OLDKEV01");
SetLineTexture(505,SIDE_FRONT,TEXTURE_MIDDLE,"OLDYHOLL"); //Why no, i'm not calling him old...
}
}

Something like this would work, I think....

**Comment by Blue-Shadow** [comment]
By "credits", he means the money items you pickup throughout the game :P

**Comment by Kyle873** [comment]
He is.

I'm closing this because you can just go back in git history, get the old sprites, and do this yourself if you really want.
