### ISSUE TITLE
Arena Round Tags are also a bit off

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#19]
Not a major problem, I know, but i've also noticed that sometimes the readout for a arena battle's current round will have it categorized as "none". I presume this is to note the fact that no extra environmental hazard is introduced. But it doesn't show up all the time.

Also, it sometimes is added onto rounds that actually do have something going on, such as a blackout.

**Comment by Kyle873** [comment]
Because of a >= instead of >, of course.
