### ISSUE TITLE
Arena Round starts are off kilter again/Can't buy Armor Bonuses from the shop

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#20]
Gonna start packing these together, I guess.

The old problem I mentioned about replaying old arena rounds and the round being already over when I activate the arena? That's back.

Secondly, I can't buy Armor Bonuses from the shop. Shop Anywhere is off, but i'm at the Outpost. If I do "buy" an armor bonus from the shop, money is deducted, but the armor bonus doesn't show up anywhere, not on the ground and not in my pickup messages. Also wearing Gothic Armor that is somewhat damaged. No, the durability of said armor did not improve.

EDIT: Not just armor bonuses. Can't buy ammo either. Same problem.

**Comment by Kyle873** [comment]
1. This isn't a bug, it's intentional so waves don't start immediately and you have breathing time. Especially in multiplayer cases where multiple players want to take positions in the Arena first before starting.

2. If Shop Anywhere is off and you make a purchase, it appears on the shop counter.
