### ISSUE TITLE
(SUGGESTION)Limit DRLA Assembly Tracking Map/Computer Map learning by player rank

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#21]
I know this is technically more DRLA's gig, but it does have something to do with DRPG and I figured the suggestion would be better placed in here.

That moment when you immediately walk into a room, pick up a red computer, and learn how to make nano-ammo weapons.

I was thinking it might help the balance a bit if the random assemblies a player can learn from one of the red computers was limited by the player's rank. Such as 0-2 for basic, 3-6 for advanced, and anything beyond that having the possibility of master assembly learning.

Just thought it might be worth mentioning.

**Comment by Kyle873** [comment]
No.
