### ISSUE TITLE
Crate "use zone" too big?

### ISSUE THREAD

**Issue by tehvappy50** [Kyle873/DoomRPG#23]
Whenever a crate replaces something (like a backpack), and it's right by a switch and you try to use said switch, you end up opening the crate instead. That has effectively rendered me stuck in one of the secrets in cchest.wad map02 unless I disable clipping with idclip. It also happened in map27 in the same pwad, but it wasn't a big deal considering I just high jumped through the level.

**Comment by Kyle873** [comment]
Yeah, this is a fair point. I think I'll try like, halving the crate radius and see how that goes over.

**Comment by Kyle873** [comment]
Okay, so I've worked around this somewhat by disallowing you from opening empty crates. Hopefully that will be good enough for now.
