### ISSUE TITLE
Loading character: HP and EP issues

### ISSUE THREAD

**Issue by bofubutt** [Kyle873/DoomRPG#24]
I've been using the same character through each of the Doom IWADs and have gotten up to Level 85, with all stats maxed out. However, when I load this character into a new session, I end up dying instead, with health going into the negative quintuple digits and EP doing something similar. When I had loaded my character previously, I had ended up with about 10x the health that I should have had. My credits, skills, and inventory don't appear to be any different, but I can't really check since when I load my character, I die immediately and don't have any Continues to keep me from resetting.

EDIT: Tried a few workarounds, such as putting a Continue in my inventory before loading, using Buddha and God Mode when loading, and using the "Resurrect" command. None worked; Resurrect resurrected my character, but made me unable to open the menu and seems to have reset the stats.

**Comment by Kyle873** [comment]
This happened because of an oversight in the HP/EP scaling code which was totally broken and I didn't even notice. It's been fixed now which should hopefully solve the above problems.
