### ISSUE TITLE
Invisibility Vial?

### ISSUE THREAD

**Issue by Blue-Shadow** [Kyle873/DoomRPG#25]
See the edit in this [post](http://forum.zdoom.org/viewtopic.php?p=821726#p821726).

**Comment by Kyle873** [comment]
Since I have absolutely no way to reproduce this or even a hint at where to even begin looking, I'm going to close this unless something like it happens again.

**Comment by Blue-Shadow** [comment]
See [this line](https://github.com/Kyle873/DoomRPG/blob/master/DoomRPG/scripts/ItemData.ds#L155) in `ItemData.ds`

**Comment by Kyle873** [comment]
Well, I'm a colossal idiot. Fixed.
