### ISSUE TITLE
negative stat starts cost negative modules

### ISSUE THREAD

**Issue by helpiminabox** [Kyle873/DoomRPG#30]
I started a new game and set all the stats to their minimum values. For the ones that go to -100, the module cost to upgrade them is negative, which is treated as free by the code. In addition, if natural leveling is on, the stats automatically go to -43 and upgrading a negative stat a couple times shoots it up to the cap for the level the character is.

**Comment by Kyle873** [comment]
Yeah, there's still a few rough edges to iron out with the startup stuff. I'll get to it tomorrow when I've actually had some sleep. That or @Pink-Silver might fix them first.

**Comment by Kyle873** [comment]
Yup. Totally ninja'd be fancy pointer wizardry.
