### ISSUE TITLE
Suggestion: Colorblind Option

### ISSUE THREAD

**Issue by helpiminabox** [Kyle873/DoomRPG#31]
This is mostly a repost from the forum, with a couple of edits, that I'm putting here to make sure it gets a proper response, even if it's no.

I'm severely colorblind. There are tons of shades of colors that I can't tell apart all over the spectrum, so when I'm doing the crate hacking minigame I only see 4 unique colors. However, looking at the code for it, I'm guessing there are 8, 1 for each effect. All I really want to be able to enjoy the minigame more is seperate patterned graphics for positive and negative effects to give more differentiation between them, since it's a little frustrating to seemingly figure out what color does what, then have a "safe" color explode the crate.

**Comment by Pink-Silver** [comment]
Addressed in https://github.com/Kyle873/DoomRPG/commit/48826d2c5fe282f43ab62cb72d8966a121873cbc
