### ISSUE TITLE
Using Transport skill on MAP29/MAP30 causes an error

### ISSUE THREAD

**Issue by bofubutt** [Kyle873/DoomRPG#32]
Tested with both doom2.wad and plutonia.wad. Using the skill to attempt to transport back to the UAC Outpost from MAP30 causes an error that states, "Unable to load map ' to select stim size '" or another similar error. Using it from MAP29 doesn't take you back to the UAC Outpost as it should, instead taking you to a different map (MAP02 in Doom, MAP20 in Plutonia), and attempting to use the skill from that map causes the same error.

(As an aside: it would be nice if there were a Paypal where we could support development. This mod has breathed a lot of new life into the game for me and kept me entertained.)

**Comment by Pink-Silver** [comment]
Fixed as of https://github.com/Kyle873/DoomRPG/commit/e3f0e628cc8080ac11813c621bf43b11e3ba4c70
