### ISSUE TITLE
Losing Regeneration XP when natural stat leveling in ON

### ISSUE THREAD

**Issue by Sirdec** [Kyle873/DoomRPG#33]
When Health is over maximum from soul spheres and so, and EP is not you actually lose regeneration xp. Easy to notice when playing throught Doom1.

On a side note being in the menu doesn't pause xp gains for regeneration/capacity. Not sure that would be a bug though

**Comment by Pink-Silver** [comment]
Fixed as of https://github.com/Kyle873/DoomRPG/commit/0ed90915f8c9bf905cb2a2ad3d57a82eed35b669
