### ISSUE TITLE
Character save data not transferring after game update.

### ISSUE THREAD

**Issue by mmx4eva** [Kyle873/DoomRPG#34]
I have been using the doom rpg launcher since january of this year and have been loving it since. Before choosing the update game option I backed up my character using the save character option as usual, but after the update I keep getting a save data outdated error. Is there another way of saving my progress or some migration tool? I just find it way too hard to start all over since I've already reached such a high level and collected so much gear.

**Comment by Kyle873** [comment]
No. This means there was a critical change in the save data that means it can no longer be loaded.

**Comment by mmx4eva** [comment]
So would this happen every time there's a critical update? It seems really inconvenient to have to lose all of your progress every time a major bug fix is released.

**Comment by Kyle873** [comment]
Yes. This is how things work and I cannot do anything about it due to all the limitations of the engine.

**Comment by mmx4eva** [comment]
Ok no problem. I just find it hard to get back to lv 50+ and reacquire the gear and legendary weapons I found. In any case, its a great mod. Keep up the awesome work.
