### ISSUE TITLE
Runaway scripts being terminated

### ISSUE THREAD

**Issue by tehvappy50** [Kyle873/DoomRPG#42]
"::ShopItemAutoHandler" gets terminated when you try to auto-store items in the outpost when burned out (EP doesn't decrease when storing/withdrawing items in the outpost so it shouldn't need to do EP checks). "::MonsterInitStats" gets terminated sometimes when starting a level on Hell difficulty.

**Comment by Pink-Silver** [comment]
Fixed ShopItemAutoHandler runaway in https://github.com/Kyle873/DoomRPG/commit/52e2e22198a421f0c6bed00b754459541055d523

**Comment by Pink-Silver** [comment]
Fixed MonsterInitStats runaway in https://github.com/Kyle873/DoomRPG/commit/ba0d12732fd0ce60b1d9cdae4594f3947ecd9e72
