### ISSUE TITLE
RLWeaponLimit sometimes isn't updated when looting weapons from crates

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#43]
If the player's rank is at least 1 (Private), and one loots a weapon from a crate, the HUD weapons counter does not increase. If the weapon is of a type that's set to auto-sell, the HUD weapons counter will *de*crease instead!

To reproduce:

1. Run DRPG with DRLA. (For reference, my configuration is below.)
2. Change your starting settings so that your starting rank is at least 1.
3. Start a new game.
4. `summon DRPGCrate`. Repeat if needed until you get a crate containing at least one weapon.
5. Loot the crate. Take the weapon. Observe the counter not changing.

My environment:

* Windows 7 64-bit
* GZDoom gfbefe13
* Doom 2 IWAD from Steam
* DRL Arsenal 7.94
* DRPG a4e1bb68

Executable and parameters:

* `C:/Program Files (x86)/gzdoom-g2.1.pre-1159-gfbefe13/gzdoom.exe`
* `-iwad`
* `C:/Program Files (x86)/Steam/steamapps/common/doom 2/base/DOOM2.WAD`
* `-file`
* `C:/Users/alex/AppData/Roaming/Doom/WADs/DoomRL Arsenal Beta 7.94.pk7`
* `C:/Users/alex/AppData/Roaming/Doom/WADs/DoomRL Monsters Beta 5.2.pk7`
* `C:/Users/alex/AppData/Roaming/Doom/WADs/DoomRPG/DoomRPG`
* `C:/Users/alex/AppData/Roaming/Doom/WADs/DoomRPG/DoomRPG-RLArsenal`
* `C:/Users/alex/AppData/Roaming/Doom/WADs/DoomRPG/DoomRPG-RLMonsters`
* `-gl3`

**Comment by Pink-Silver** [comment]
Fixed in https://github.com/Kyle873/DoomRPG/commit/6f6c7270875db9986a282793dea648e97487d5b7

For reference, it has nothing to do with crates at all, but having Auto-Sell on for weapons or doing so via the run key caused the flag to be taken away without selling the weapon if you were below rank 1.

**Comment by argv-minus-one** [comment]
This problem is **not** fixed as of c8a9f1daad.

Following the above steps does not increment the weapon counter when looting the crate. It stays the same if the weapon looted is not marked auto-sell, and it *de*crements if the weapon is marked auto-sell (if rank ≥ 1). One thing did change, though: the bug now appears at rank 0 as well.

**Comment by Pink-Silver** [comment]
Actually it **was**, in https://github.com/Kyle873/DoomRPG/commit/765af2450b4eab3fba7e32daf3d08e518218aa98 in drlaupdate, which is why it did not happen for me nor Kyle. I caught this and pulled the fix from there for https://github.com/Kyle873/DoomRPG/commit/6a87d82c5715d5add61221285091ebe11d3eee7e.

**Comment by argv-minus-one** [comment]
It works for me too, now! Yay! Thank you. :)
