### ISSUE TITLE
Hell Unleashed apparently doesn't get cleared on level exit

### ISSUE THREAD

**Issue by tehvappy50** [Kyle873/DoomRPG#45]
When you finish a level with the Hell Unleashed event active, the event apparently isn't cleared (the level transporter in the outpost still shows the event), and the counters are still going if you reenter the level.

**Comment by Pink-Silver** [comment]
Intentional, not a bug. The counters are tied to your luck, so if you choose to stick around, the monsters will start to drop rarer items more and more often.

Also, remember to actually label reports instead of leaving them blank, thanks.
