### ISSUE TITLE
Outpost stim injector is ridiculously overpowered.

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#47]
I used the Outpost stim injector to give my character an edge in an especially difficult map (Speed of Doom MAP32). Threw damn near everything I had into it. The result: I was finding gobs of aug canisters and other super-rare items for the better part of an hour!

As amusing as the subsequent rampage was, I may as well have used `god;give all` instead. Totally overpowered. There really should be some sort of limitation on using it, IMHO. Perhaps by making it kill you if you try to use too much at once?

**Comment by Kyle873** [comment]
Oh yeah, I know, believe me. I just haven't come up with a good way to limit yet. Flat out killing you is the lazy way out, I'd like to come up with something better. That and flesh out the immunity system some more. I honestly just wrote that up in like 10 minutes just to mitigate some of the issues.

**Comment by Kyle873** [comment]
I just decided to nuke the system entirely.
