### ISSUE TITLE
Turret reflective armor property sometimes gets transferred to the player.

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#49]
Under some circumstances, when a turret with reflective armor is destroyed, the *player* becomes reflective.

I can reproduce it in an existing save, but I can't reproduce it in a new game for some reason. [Here's a zip containing that save file](https://infotomb.com/72qw8.zip), in case you want to examine it yourself. That save was made with GZDoom gfbefe13 and the following WADs:

* doom2.wad from Steam
* [btsx_e2.pk3](http://www.best-ever.org/download?file=btsx_e2.pk3)
* DoomRL Arsenal Beta 7.94.pk7 ([the downloaded 7z file](https://www.dropbox.com/s/gyipbtmzah5yt11/DoomRL%20Arsenal%20Beta%207.94.7z?dl=1) renamed to pk7)
* [DoomRL Monsters Beta 5.2.pk7](https://www.dropbox.com/s/3o8jw52zoxcbkee/DoomRL%20Monsters%20Beta%205.2.7z?dl=1)
* DoomRPG/DoomRPG (90a4e169)
* DoomRPG/DoomRPG-RLArsenal
* DoomRPG/DoomRPG-RLMonsters

To reproduce the bug with this save, just summon a Cyberdemon or something and let it kill the turret. Then you should be able to shoot a rocket at a nearby wall without taking splash damage, which is a side effect of being reflective.

I know this isn't much to go on, but as I said, I can't seem to reproduce it in a new game. Don't know why. I thought I'd better report what I do know, at any rate.

In case anyone else runs into this bug and wants a workaround: you can remove the reflectiveness with `give DRPGGreenAuraRemover`.

**Comment by Pink-Silver** [comment]
Fixed in https://github.com/Kyle873/DoomRPG/commit/38adc34eb34330a30d20813b25cfd63f03043490
