### ISSUE TITLE
HUD notifications of stat increases sometimes show incorrect name.

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#50]
Rarely, when my character gains a stat increase (either by spending modules or by natural stat growth), the resulting floating HUD notification thingy shows a completely unrelated actor class name instead of the stat name. So, for instance, it just showed “DRPGSTIMPACK+” instead of “STRENGTH+”. The stat increase does still happen as normal, and the correct icon for the stat is shown, but the name is wrong. Increasing the same stat repeatedly shows the same incorrect name (e.g. increasing strength repeatedly gives multiple “DRPGSTIMPACK+”es).

When this happens, it seems to persist, but changing maps (transporting back to the Outpost, exiting the map, `changemap`, or even `changemap`ping to the *same* map) seems to make it work correctly again.

Exactly which names get shown seems to vary. This time I'm getting health and armor items (stimpack, blue armor, etc), but I remember once seeing “RLHIGHPOWERNUCLEARBFG9000+” (or, well, the part of it that fit on the screen) show up.

My configuration is currently:

* GZDoom gfbefe13
* doom2.wad from Steam
* DoomRL Arsenal Beta 7.94.pk7 ([the downloaded 7z file](https://www.dropbox.com/s/gyipbtmzah5yt11/DoomRL%20Arsenal%20Beta%207.94.7z?dl=1) renamed to pk7)
* [DoomRL Monsters Beta 5.2.pk7](https://www.dropbox.com/s/3o8jw52zoxcbkee/DoomRL%20Monsters%20Beta%205.2.7z?dl=1)
* DoomRPG/DoomRPG (5bfa464, but it's happened with older versions too)
* DoomRPG/DoomRPG-RLArsenal
* DoomRPG/DoomRPG-RLMonsters

I have seen it happen with many different map sets, so I doubt it has anything to do with that.

**Comment by Pink-Silver** [comment]
Can't fix this proper right now, and here's why - The compiler we're using, dh-acc, has known bugs with managing ACS VM memory, and we plan to move away from it to a proper C compiler for ACS called GDCC, which is a more up-to-date rewrite of it, but having two separate branches to maintain, we cannot do that until the drlaupdate branch is merged together with the master, which requires that Yholl release the next version of DoomRL Arsenal which is what the branch is meant to support. So for now, I'm going to have to just leave this open.

**Comment by Kyle873** [comment]
Unless this comes up again in the gdcc_conversion branch, I'm going to assume the move over to GDCC has fixed this one.

**Comment by Pink-Silver** [comment]
That was fixed in https://github.com/Kyle873/DoomRPG/commit/ce432c24d649c5cc5b02dfe75f233cf1071b1205 but GDCC doesn't need the fix at all so it's gone forever.
