### ISSUE TITLE
Monsters' EP-draining auras seem overpowered.

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#55]
I'm not sure if this is intentional, but the EP-draining auras on some monsters seem pretty overpowered. They render skills pretty much unusable, there's no way to avoid them, and the only ways to resist them (as far as I know) involve using skills that also consume a lot of EP.

This is especially obvious on Hell and Armageddon difficulties, where such monsters are common, and because of the constant influx of new monsters, you can't even find a secluded spot to use focus mode and use some skills before getting back into the fight. As a result, skills (with non-zero EP costs, anyway) are pretty much unusable on these difficulties.

**Comment by argv-minus-one** [comment]
I've run a few maps on Hell difficulty since posting this issue, and the EP drains don't seem *too* common. Still, when they do show up, they're a major pain.

**Comment by Pink-Silver** [comment]
If you're concerned about EP to such an extent, you should take precautionary measures when on aura missions and the highest skills - secure places to focus when not in battle, and put a point into Disruption to disable auras when fighting them in enclosed spaces - it's only 50 EP initially, which considering you get +10 per stat point, you can rack up quite a few uses of it very quickly, especially if you can get your hands on an augmentation early on from bosses, as just one level will double your EP pool instantly.

If you're in an actually dangerous situation, also remember that you can overdrive skills to force-use them once even if you don't have the pool for them, and burn-out can be cured with detox stims, so they in combination can definitely save you if running away is definitely not an option, like with shadow auras and open areas.

**Comment by Kyle873** [comment]
I'm going to leave this alone. @Pink-Silver gave some good advice on how to combat aura enemies, particularly more dangerous ones like the drainers. I think it's fine the way it is right now, it just requires being more strategic and using many elements together in order to surpass them.

**Comment by argv-minus-one** [comment]
Sounds good. Perhaps that advice should be added to the wiki?

**Comment by Kyle873** [comment]
Not a bad idea. Honestly, the wiki is pretty out of date in certain respects. I've been the only one so far to ever edit it, but I have nothing against others editing, contributing to or updating it as well.
