### ISSUE TITLE
Cannot equip shield-compatible armor while a shield is active.

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#57]
When the “shields remove armor” option is turned on and a shield is active, I cannot equip armor, even if that armor is [compatible with a shield](https://github.com/Kyle873/DoomRPG/blob/master/DoomRPG/scripts/Shield.ds#L1441). Instead, I must deactivate the shield, equip the armor, then activate the shield again. This seems incorrect.

**Comment by Kyle873** [comment]
This is because there is a shitton of hacks currently involved with the system that will be resolved when DRLA 1.0 comes out.
