### ISSUE TITLE
Activating a shield does not remove armor if it has a set bonus.

### ISSUE THREAD

**Issue by argv-minus-one** [Kyle873/DoomRPG#62]
When wearing an armor set (e.g. Tactical Armor + Tactical Boots), activating a shield does not remove the armor, even if the relevant option is enabled. The armor continues to provide protection and its set bonus, as usual.

Attempting to remove the armor while in this state gives a message that “you aren't wearing any armor”, even though that isn't true, since the armor didn't actually get removed.

Attempting to remove the boots while in this state works, but the armor remains equipped. An armor counter reading “99999” appears, and will decrease upon taking damage, like it would for ordinary destructible armor. Deactivating the shield at this point causes the armor counter to disappear again, and activating the shield once more will correctly remove the armor.

**Comment by Kyle873** [comment]
This is all because of hacks currently in place to support 7.94. Once everything is moved to 1.0 they will go away.
