### ISSUE TITLE
"Kill Monsters" permanently kills off your turret as well

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#68]
So, I was going through one of the maps with a monster-related event enabled, powering through it with the help of a shell turret. Couldn't find the last one no matter what, so I figured i'd just use the ol kill monsters cheat and move on. Unfortunately, this also killed off the turret, despawning it.

This really wouldn't be an issue worth mentioning, if it wasn't for the fact that the turret is now permanently gone. I can't use the Turret command to resummon it. I already checked, all the maintenance timers are at zero.

I suppose this is one heck of a misadventure, but now I seem to be without my turret for the rest of this wad. This confuses me seeing as how it's just the turret dying as if it ran out of health. Or...is it?

While i'm on this topic, anyone have any idea how to restore turret functionality? Maybe a give command of some sort?

**Comment by argv-minus-one** [comment]
Try installing a level of the “Armor Plating – Reinforcement” upgrade. That helped one time when my turret got wedged like that (though for some different, still-unknown reason).

**Comment by Silentdarkness12** [comment]
@argv-minus-one I already have Armor Plating-Reinforcement at maximum, so that isn't gonna help. I've tried upgrades, they don't let me re-summon the turret.

**Comment by argv-minus-one** [comment]
I have opened pull request #77, with a workaround for this issue.
