### ISSUE TITLE
Massive, unknown slowdown caused by Thinkers in some maps?

### ISSUE THREAD

**Issue by DarkPulse** [Kyle873/DoomRPG#79]
I've been doing a playthrough with DoomRPG + DRLA on the slaughterwad Chillax. Some maps throw thousands of monsters at you (and obviously those can get fixed by reducing the monster count in the DoomRPG options), but one map on it - MAP32 - slows to an utter crawl for no discernable reason that I can think of, and has effectively brought my game to a screeching halt - quite literally.

The map itself isn't overly complex. It's got about 600 Monsters on it on Nightmare/Ultra-Violence difficulty, nearly 500 of them are Archviles and the rest are Cyberdemons. The map isn't doing a lot of crazy geometry or anything like that, and it runs just fine without the mod enabled. It also runs at the same poor performance if DRLA is disabled but DoomRPG is not.

![chillax-v9 7 2 wad_map32_noalpha](https://cloud.githubusercontent.com/assets/5454684/9451070/72145b0e-4a7a-11e5-8a32-467b73605184.png)

Based on some help on the ZDoom forums, I was given a suggestion to test the Think time and that confirmed it was the issue - the think time for the one screenshot I could get showed a time that was nearly 8 seconds to render (although it took about a good 15 seconds to actually show that to the screen). Something with this map is making the thinkers go absolutely crazy, and I simply can't figure out if anything can be done about it. Even if I reduce the monster count to 10% (60 monsters), I still get the horrible performance.

![screenshot_doom_20150816_233650](https://cloud.githubusercontent.com/assets/5454684/9451086/8838859a-4a7a-11e5-9559-cefded4b079c.png)

My system is anything but a toaster (i7 2600-K overclocked to 4.4 GHz, GTX 690 for a GPU) so I know it's not that.

I have the August 6th SVN build of GZDoom, and the July 3rd build of DoomRPG. The version of Chillax I'm using is v9.7.2, and I can provide a savegame if for some reason this can't be replicated by someone else.

**Comment by Kyle873** [comment]
So yeah, there's absolutely nothing we can do about this. Basically, if the conversion of the code to the new compiler doesn't help, nothiing will, short of not having a toaster.

**Comment by DarkPulse** [comment]
That's the weird thing though. The map before then had thousands of monsters, and yet it didn't take that long to tick a frame (in fact, it was just fine in terms of framerate).

But yet, here on this specific map only, I can turn it down to 10% of the normal monster amounts (it then becomes 60, which shouldn't be a problem for it to process) and it still goes into the toilet.

Could it be something to do with the amount of Cyberdemons, since usually those are one of the two monsters that can become named and thus have more scripts run on them or something? Though then again, the map before then also had no shortage of Cyberdemons - at least a few dozen.

**Comment by Kyle873** [comment]
AFAIK It probably has to do with LoS checks between actors. This is why wads such as nuts.wad absolutely tank in ZDoom and derivatives, because checks will exponentially pile up the closer and more clustered groups of enemies are together to the point where it just can't keep up anymore.

I might be off though, and will ping @Edward850 for a real detailed and technical explanation regarding the actor ticking.

**Comment by Edward850** [comment]
Actors don't LoS each other by default, for precisely that reason. Only the player. Unless it's something you've added, it's not tge cause  (especially with just 60 monsters).

**Comment by DarkPulse** [comment]
Well, in some maps I definitely had to turn the monster numbers down (MAP13 or 14 has way too many monsters and it will quickly shit itself otherwise). This specific problem is in Chillax's MAP32, though. As I said, I have a savestate that "should" bring you right there (it'll really be on MAP31, but walk forward to exit to 32), if for some reason simply warping to 32 directly doesn't cause the issue.

**Comment by Pink-Silver** [comment]
This isn't happening on the GDCC branch, by the way, so this should be totally gone once that hits master.
