### ISSUE TITLE
Selling shield parts makes the game think you have fewer weapons than you do (with Doom RLA)

### ISSUE THREAD

**Issue by bofubutt** [Kyle873/DoomRPG#80]
I'm playing with the most recent GZDoom, Doom RPG, and Doom RLA (plus HUD and monster pack) releases using the Ultimate Doom wad and the Doom 1 compatibility folder. For most of the game, I was limited to the normal six weapons. However, upon selling some extra shield parts from the Shop menu, I noticed that I was suddenly able to pick up more weapons. After some testing, I noticed that, any time I sold a shield part, my weapon count went down, all the way down until the weapon icon disappeared. I still have all of my weapons, however.

Dropping all of my weapons (after getting rid of the extras) and picking them back up solved the issue, but I imagine only until I sell some more shield parts.

**Comment by Pink-Silver** [comment]
https://github.com/Kyle873/DoomRPG/commit/ab67ac81ffc26231df61e91c1f583a51bdda2ec5 (and https://github.com/Kyle873/DoomRPG/commit/af033fe1082542993fc1ea1d7b11c9f333a14cb2 )
