### ISSUE TITLE
A Cyberdemon spawns inside the UAC base if you spend too long in the arena

### ISSUE THREAD

**Issue by bofubutt** [Kyle873/DoomRPG#81]
While trying to level myself up so that I could clear an Armageddon event, I heard the laugh of a Nightmare Cyberdemon after I cleared about 30 waves. Thinking nothing of it, I cleared a few more and left the arena to go try again, only to find that a Nightmare Cyberdemon ("Hunter Cyberdemon") had spawned in the UAC base starting area and was stomping around in the teleporter area. The friendly marines and turrets didn't respond to it, but it certainly was hostile. To make matters worse, when I retaliated, the base immediately went on lockdown mode, and all of the marines turned hostile.

This pretty much forced me to load my last auto-save (after the Cyberdemon had spawned) and use the Teleport skill to get back to the level. I can definitely see the potential in spawning a powerful enemy to hunt down a player if they massacre a lot of enemies, but unless this is some kind of Easter Egg that I just happen to keep on getting, then maybe the enemy shouldn't spawn in the UAC base.

(That, or have the marines actually attack it instead of standing there passively while it creams me with a particle beam, then getting mad when I fire back at it.)

**Comment by Pink-Silver** [comment]
Closing this because it is in fact a DRLA bug, not a DRPG one and therefore cannot be fixed on this end, and has to be fixed on the other. I brought up the problem with Kyle and Yholl so they're now both aware of it.
