### ISSUE TITLE
Armour mod pack limiter isn't removed on selling/storing

### ISSUE THREAD

**Issue by tehvappy50** [Kyle873/DoomRPG#83]
When acquiring an armour mod pack and then selling/storing it afterwards, the game will still think you are carrying one, rendering you unable to pick up another armour mod pack.

**Comment by Silentdarkness12** [comment]
I can say that it's not just the OP having both of these issues.

I have Augmentation Slots set to 3 to start with. Ingame, I start with zero. Which makes for a harder early game, obviously.

**Comment by Pink-Silver** [comment]
Please report separate issues separately, thank you. I split off your other report about starting options not working into https://github.com/Kyle873/DoomRPG/issues/86.

**Comment by Kyle873** [comment]
Yup, found the issue. Silly oversight on my end.
