### ISSUE TITLE
Idea: Please make a Zandronum (Lite) version

### ISSUE THREAD

**Issue by DartPower** [Kyle873/DoomRPG#84]
Idea: Please make a Zandronum (Lite) version
I just cant normally play multiplayer on ZDooM/GZDooM
I dream and want normally multiplayer, but the all functions of this wad maked for final (git) versions of ZDooM/GZDooM
I dont know, too hard porting for zandronum or not... Please answer me for this idea, i dream version for zandronum :(

**Comment by Silentdarkness12** [comment]
The DRPG launcher has an option to quickly get multiplayer working. That's all you can hope for, really.

DRPG is quite oversized. I'm not a dev, but I have the distinct feeling he's not going to make a light version for Zandronum.

Zandronum still isn't even fully up to date.

**Comment by Pink-Silver** [comment]
The long version is that this requires very advanced features for very specific reasons, and porting it to the current Zandronum would be literally impossible. If Zan catches up to current ZDoom features, it *might* be considered, but even then it's a long shot and will most likely not happen.

The short version is that it's not happening, sorry.
