### ISSUE TITLE
Artifact Guardian can enter Outpost (Mechanical Spoiler)

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#85]
With DRLA, when you kill monsters in the Outpost Arena, when a wave ends, it is possible for the Artifact Guardian to spawn in the Outpost. This is hilarious. But it's also a problem because it's a guarantee that the UAC gets pissed off at you.

Frankly, while i'm on that topic, Outpost Invasion event. Should totally be a thing.

**Comment by Kyle873** [comment]
FFS this is also DRLA related. At least fucking report this shit in the right place.
