### ISSUE TITLE
Spawns in Arena affected by missions

### ISSUE THREAD

**Issue by wu4** [Kyle873/DoomRPG#88]
I'm unsure if all missions that change spawns affect the Arena, but having a "Kill Auras" mission active will noticeably increase the number of Auras showing up in each wave.

**Comment by Pink-Silver** [comment]
We're going to be scrapping the current Arena code soon.

**Comment by Pink-Silver** [comment]
Fixed in gdcc_conversion: https://github.com/Kyle873/DoomRPG/commit/4f4e995b5fb7e66f8260a2b35a62735522dfd9a6
