### ISSUE TITLE
Doom II vanilla compatibility issues

### ISSUE THREAD

**Issue by Talon1024** [Kyle873/DoomRPG#89]
Doom RPG with RL arsenal loaded seems to have compatibility issues with vanilla Doom II (with Xeotroid's music pack and Perkristian's HQ sounds autoloaded) that turn the game into a creepypasta story.

Apparently, you are unable to teleport to the outpost. The "transport" skill takes you to MAP02.

And if you start from the outpost, and set the skill level to easy at the skill computer, maps without events apparently begin with a "powermod" event, which greatly increases the number of credits and supply crates (both hackable and normal) lying around, as well as greatly bolsters enemy stats.

But if I load another IWAD or mod, such as Memento Mori II (with the Doom II IWAD), Final Doom: Evilution, or Final Doom: Plutonia Experiment, everything works just fine.

BTW, I am using builds of LibDS.lib and RPG.lib that I compiled myself while porting _compile.bat to Bash on a local fork of the Doom RPG repo, as well as a Linux build of GZDoom g2.1.0 that I compiled myself.

Screenshots:
![screenshot_doom_20160222_054056](https://cloud.githubusercontent.com/assets/6550500/13215944/e211faac-d926-11e5-8233-8cd618a30a53.png)
![screenshot_doom_20160222_053029](https://cloud.githubusercontent.com/assets/6550500/13215949/eac1bbd8-d926-11e5-9776-cc75099ba509.png)
![screenshot_doom_20160222_053011](https://cloud.githubusercontent.com/assets/6550500/13215954/f62f5002-d926-11e5-95d5-c9a5cb195a5b.png)

**Comment by Pink-Silver** [comment]
Short version; Don't do that.
Long version: [gdcc_conversion](https://github.com/Kyle873/DoomRPG/tree/gdcc_conversion).

Do not attempt to compile the DH-acc version as it is massively outdated and **doesn't work**, especially under Linux. With the GDCC branch, you can compile it with [GDCC](https://github.com/DavidPH/GDCC) natively using my Python scripts.

**Comment by Talon1024** [comment]
Are you talking about a specific version of DH-acc, or the DH-acc compiler altogether? Because when I did my port of _compile.bat to Bash, I removed DH-acc and replaced it with a git submodule (that's like a shortcut or symbolic link) to the official DH-acc GitHub repo.

**Comment by Pink-Silver** [comment]
As a whole. The last version of DH-acc was abandoned months ago, and DavidPH has announced that it is end-of-life and he will no longer be supporting it, hence our conversion branch.
