### ISSUE TITLE
DoomRPG in combination with DoomRL Arsenal

### ISSUE THREAD

**Issue by FreaKzero** [Kyle873/DoomRPG#90]
Hi guys!

Im working now since a longer time on an Doom Frontend - and wanted to integrate an easy way to launch DoomRPG with DoomRL Arsenal (https://github.com/FreaKzero/ssgl-doom-launcher).

Now i saw that you guys changed from zDoom compatibility to gzDoom compatibility - and when im trying to launch DoomRPG with DoomRL Arena (as described in your Wiki) it runs even stable BUT im getting alot of "Numeric type expected" errors - and it seems as i cant buy any Weapon from the shop ? (seeing a correlation there)

Tried it today with the latest gzDoom Devbuild (downloaded today) - what gzDoom and/or DoomRL Arsenal (downloaded the version from zDoom Forums) version is needed for that combination ?

A short part of the log:
```
Script error, "doomrl_arsenal_1.05.wad:DEC_SCPP" line 1459:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BSCH" line 99:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BSCH" line 106:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BSCH" line 113:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BSCH" line 120:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BULR" line 104:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BULR" line 111:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BULR" line 118:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_BULR" line 125:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUTS" line 119:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUTS" line 130:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUTS" line 141:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUTS" line 151:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUTS" line 153:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUTS" line 154:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUDS" line 146:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUDS" line 157:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUDS" line 168:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUDS" line 178:
Numeric type expected
Script error, "doomrl_arsenal_1.05.wad:DEC_AUDS" line 180:
```

**Comment by Kyle873** [comment]
So does any of this happen when using the stable 2.1.0 release of GZDoom?

Don't use the devbuilds. They're all absolutely fucked beyond belief right now and break all sorts of stuff in both Doom RPG and DRLA that we can't do anything about.

**Comment by FreaKzero** [comment]
Man, the Numeric type errors are gone with 2.1.0, i used the newest devbuilds because every forum suggests that.

Thanks!

**Comment by Kyle873** [comment]
Understandable, even we suggest it. As of late though things have really hit the fan ever since they merged the experimental scripting branch into master. We've all stayed away from them for development reasons until they sort out the issues, which will take god knows how long.

**Comment by FreaKzero** [comment]
You guys should make an entry in the wiki or readme for that imho, something like "Tested with Versions of gzDoom >= Version

**Comment by FreaKzero** [comment]
@Kyle873 
Have to say... im a "noob" what this mod combinations belongs - just came to it because someone wanted that feature (btw.. you guys did an awesome job)

But - even i dont get this errors anymore at start i cant buy any "special" weapon - i know this has maybe to do with DoomRL Arsenal - but maybe you know what this can be ?

http://giphy.com/gifs/3o7abpt3L0KF0Gm8b6

**Comment by Pink-Silver** [comment]
This is not a bug. The weapons are clearly greyed out, you are not allowed to purchase them until you find a rare key item first.

**Comment by FreaKzero** [comment]
k thank you - sorry for that false alarm - as i said dont know anything about this mod combo.
