### ISSUE TITLE
FPS Issue with func monster population in % more than 100%

### ISSUE THREAD

**Issue by WarezzK** [Kyle873/DoomRPG#91]
When i change in difficulty settings "Monster Population" more than 100% i have very unstable game and heavy FPS drop. It happens in latest 2.1 svn GzDoom and without any mods like RL etc. even older GzDoom. Even delete config.ini. It happens on any map (D1,D2, Plutonia...) Problem is probably with spawning. Monster have not space on map in specific place. You must kill already spawned monster then spawn new. When you kill all monsters, then FPS go to normal. Excuse me if i have bad English - I'm CZECH :)

Anyway, keep it work it's fantastic mod.

**Comment by subenji** [comment]
This was fixed with https://github.com/Kyle873/DoomRPG/commit/adb941aeefc14eaa4dca1eb6650854bf822ca06c, it was a looping script responsible for spawning extra enemies that was doing too much in one loop.
