### ISSUE TITLE
DRLA+DoomRPG crashing on launch

### ISSUE THREAD

**Issue by misterazrael** [Kyle873/DoomRPG#99]
Any time I try to load both DRLA+DRPG, I always crash before the game even starts.

I have tried this on different versions of GZDoom, including 2.1.0 and several different dev releases just to make sure, same error every time.

I can launch either DRPG or DRLA on their own perfectly fine, it's just when I try to combine them that this happens.

I've attached a log so that someone can look at it, but the error is different on GZDoom, so I'll add that here too.
[DRPG Launcher Log.txt](https://github.com/Kyle873/DoomRPG/files/517830/DRPG.Log.txt)
[GZDoom Log.txt](https://github.com/Kyle873/DoomRPG/files/517833/GZDoom.Log.txt)

I should also add that I've completely deleted the DoomRPG folder and redownloaded it to see if that'd fix it, but it didn't.

**Comment by WarezzK** [comment]
Yes. Same problem.

**Comment by doomsguy214** [comment]
hmm trying copying following code in powerups
actor InvulnerabilitySphere2 : CustomInventory Replaces DRPGInvulnerabilitySphere
{
	Tag "Invulnerability Sphere - Invulnerability for 30 seconds"
	
    Inventory.PickupMessage "You got an Invulnerability Sphere!"
	Inventory.PickupSound "powerups/protect"
	Inventory.UseSound "powerups/protect"
	Inventory.Icon "PINV"
    
    -COUNTITEM
    
    States
	{
    Spawn:
        TNT1 A 0 NoDelay ACS_NamedExecuteAlways("ItemInit", 0)
        PINV ABCD 6 Bright
        Goto Spawn+1
	Pickup:
        TNT1 A 0 A_JumpIf(CallACS("GetStimPowerupActive"), "PickupFail")
		TNT1 A 1 A_TakeInventory ("PowerRLLavaSetBonusInvulnerable")
		TNT1 A 1 A_TakeInventory ("PowerInvulnerable")
		TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
		TNT1 A 1 A_GiveInventory ("RLInvulnerabilitySphereNormal2")
		stop
		TNT1 A 0 A_GiveInventory ("RLInvulnerabilitySphereMarine2")
		stop
    PickupFail:
        TNT1 A 0
        Fail
	}
}

ACTOR RLInvulnerabilitySphereNormal2 : PowerupGiver Replaces RLInvulnerabilitySphereNormal
{
	+INVENTORY.AUTOACTIVATE
	+INVENTORY.ADDITIVETIME
	
	Powerup.Color GoldMap
	Powerup.Type Invulnerable
	Powerup.Duration -30
}

ACTOR RLInvulnerabilitySphereMarine2 : RLInvulnerabilitySphereNormal2 Replaces RLInvulnerabilitySphereMarine
{
	Powerup.Duration -45
}

actor InvulnerabilityCharge2 : DRPGInvulnerabilityCharge Replaces DRPGInvulnerabilityCharge
{
	States
	{
	Use:
        TNT1 A 0 A_JumpIf(CallACS("GetStimPowerupActive"), "UseFail")
		TNT1 A 1 A_TakeInventory ("PowerRLLavaSetBonusInvulnerable")
		TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
		TNT1 A 1 A_GiveInventory ("RLInvulnerabilityChargeNormal")
		stop
		TNT1 A 0 A_GiveInventory ("RLInvulnerabilityChargeMarine")
		stop
	} 
} 

ACTOR RLInvulnerabilityChargeNormal : PowerupGiver
{
	+INVENTORY.AUTOACTIVATE
	+INVENTORY.ADDITIVETIME
	
	Powerup.Color GoldMap
	Powerup.Type Invulnerable
	Powerup.Mode Reflective
	Powerup.Duration -30
}

ACTOR RLInvulnerabilityChargeMarine : RLInvulnerabilityChargeNormal
{
	Powerup.Duration -45
}

ACTOR BlurSphere2 : CustomInventory Replaces DRPGBlurSphere
{
	Tag "Blur Sphere - Partial Invisibility for 60 seconds"
	
	+INVENTORY.ADDITIVETIME
	+INVENTORY.PERSISTENTPOWER
	+VISIBILITYPULSE
	+FLOATBOB
    -COUNTITEM

	Inventory.PickupMessage "You got an Invisibility Sphere!"
	Inventory.PickupSound "powerups/invis"
	Inventory.UseSound "powerups/invis"
	Inventory.Icon "PINS"

	RenderStyle Translucent
	
    States
	{
    Spawn:
        TNT1 A 0 NoDelay ACS_NamedExecuteAlways("ItemInit", 0)
        PINS ABCD 6 Bright
        Goto Spawn+1
	Pickup:
        TNT1 A 0 A_JumpIf(CallACS("GetStimPowerupActive"), "PickupFail")
		TNT1 A 1 A_TakeInventory ("PowerRLLavaSetBonusInvulnerable")
		TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
		TNT1 A 1 A_GiveInventory ("RLBlurSphereNormal")
		stop
		TNT1 A 0 A_GiveInventory ("RLBlurSphereMarine")
		stop
    PickupFail:
        TNT1 A 0
        Fail
	}
}	

ACTOR RLBlurSphereNormal : PowerupGiver
{
	+INVENTORY.AUTOACTIVATE
	+INVENTORY.ADDITIVETIME
	
	Powerup.Type Invisibility
	Powerup.Duration -60
}

ACTOR RLBlurSphereMarine : RLBlurSphereNormal
{
	Powerup.Duration -90
}

actor InvisibilityCharge2 : DRPGInvisibilityCharge Replaces DRPGInvisibilityCharge
{
	States
	{
	Use:
        TNT1 A 0 A_JumpIf(CallACS("GetStimPowerupActive"), "UseFail")
		TNT1 A 1 A_TakeInventory ("PowerRLLavaSetBonusInvulnerable")
		TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
		TNT1 A 1 A_GiveInventory ("RLInvisibilityChargeNormal")
		stop
		TNT1 A 0 A_GiveInventory ("RLInvisibilityChargeMarine")
		stop
	}
} 

ACTOR RLInvisibilityChargeNormal : PowerupGiver
{
	+INVENTORY.AUTOACTIVATE
	+INVENTORY.ADDITIVETIME
	
	Powerup.Type Shadow
	Powerup.Strength 100
	Powerup.Duration -60
}

ACTOR RLInvisibilityChargeMarine : RLInvisibilityChargeNormal
{
	Powerup.Duration -90
}

actor RadSuit2 : CustomInventory Replaces DRPGRadSuit
{
	Tag "Radiation Suit - Protects against Damage Floors"

	+INVBAR
	+INVENTORY.ADDITIVETIME
	+INVENTORY.PERSISTENTPOWER
	
	Inventory.DefMaxAmount
	Inventory.InterHubAmount 1000
	Inventory.PickupMessage "You got a Radiation Suit!"
	Inventory.PickupSound "powerups/suit"
	Inventory.UseSound "powerups/suit"
	Inventory.Icon "SUIT"
	
    States
	{
    Spawn:
        TNT1 A 0 NoDelay ACS_NamedExecuteAlways("ItemInit", 0)
        SUIT A -1 Bright
        Stop
	Pickup:
		TNT1 A 0 ACS_NamedExecuteWithResult("CheckCapacity")
        stop
	Use:
		TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
		TNT1 A 1 A_GiveInventory ("RLRadSuitNormal2")
		stop
		TNT1 A 0 A_GiveInventory ("RLRadSuitMarine2")
        TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
        TNT1 A 1 A_GiveInventory ("RLRadSuitPower")
        stop
        TNT1 A 0 A_GiveInventory ("RLRadSuitMarine")
		stop
	}
}

ACTOR RLRadSuitNormal2 : PowerupGiver
{
	+INVENTORY.AUTOACTIVATE
	+INVENTORY.ADDITIVETIME
	
	Powerup.Type IronFeet
	Powerup.Duration -60
}

ACTOR RLRadSuitMarine2 : RLRadSuitNormal2
{
	Powerup.Duration -90
}

actor Infrared2 : CustomInventory Replaces DRPGInfrared
{
	Tag "Night-Vision Goggles - See in the Dark"
	
	+INVBAR
	+INVENTORY.ADDITIVETIME
	+INVENTORY.PERSISTENTPOWER
    -COUNTITEM
	
	Inventory.DefMaxAmount
	Inventory.InterHubAmount 1000
	Inventory.PickupMessage "You got a pair of Infrared Goggles!"
	Inventory.PickupSound "powerups/light"
	Inventory.UseSound "powerups/light"	
	Inventory.Icon "PVIS"
	
	States
	{
    Spawn:
        TNT1 A 0 NoDelay ACS_NamedExecuteAlways("ItemInit", 0)
        PVIS AB 6 Bright
        Goto Spawn+1
	Pickup:
		TNT1 A 0 ACS_NamedExecuteWithResult("CheckCapacity")
		Stop
	Use:
		TNT1 A 0 A_JumpIfInventory ("RLAmmochainPerk", 1, 2)
		TNT1 A 1 A_GiveInventory ("RLInfraredNormal2")
		stop
		TNT1 A 0 A_GiveInventory ("RLInfraredMarine2")
		stop
	}
}

ACTOR RLInfraredNormal2 : PowerupGiver
{
	+INVENTORY.AUTOACTIVATE
	+INVENTORY.ADDITIVETIME
	
	Powerup.Type LightAmp
	Powerup.Duration -120
}

ACTOR RLInfraredMarine2 : RLInfraredNormal2
{
	Powerup.Duration -180
}

actor Berserk2 : RLBerserk Replaces DRPGBerserk
{
	Tag "Berserk Pack - Full Health and Increased Melee Damage"
	
    -COUNTITEM
	
	Inventory.PickupMessage "You got a Berserk Pack!"
	Inventory.PickupSound "powerups/berserk"
    
    States
    {
    Pickup:
        TNT1 A 0 A_JumpIfInventory("PowerStrength", 1, 2)
        TNT1 A 0 ACS_NamedExecuteAlways("AddToxicity", 0, 10)
        TNT1 A 0 ACS_NamedExecuteAlways("AMShieldCharge", 0)
        TNT1 A 0 ACS_NamedExecuteAlways("AddHealth", 0, 100, 100)
        TNT1 A 0 A_JumpIfInventory ("RLBerserkPowersuitArmorToken", 1, "Powersuit")
        TNT1 A 0 A_GiveInventory("PowerStrength")
        TNT1 A 0 A_JumpIfInventory ("RLAmmoChainPerk", 1, 2)
        TNT1 A 0 A_GiveInventory("PowerRLBerserkResistance")
        Goto Pickup+8
        TNT1 A 0 A_GiveInventory("PowerRLBerserkResistanceMarine")
        Stop
    }
}

actor MegasphereSpawner2 : RLMegasphereSpawner replaces MegaSphere
{
    States
    {
    Spawn:
        TNT1 A 0 A_JumpIf(CallACS("DRPGCheckTiem"), 2)
        TNT1 A 0 A_JumpIf(CallACS("DRLA_specialstarts") == 2, "SpawnDuke2")
        TNT1 A 0 A_SpawnItemEx ("RLMegasphere", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION)
        TNT1 A 0 A_SpawnItemEx ("RLRandomSkullSpawner", random(-24,24),random(-24,24),0, 0,0,0, 0, SXF_NOCHECKPOSITION, 12)
        TNT1 A 0 A_SpawnItemEx ("RLMegasphereSpot", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION)
        Stop
    }
}

actor Megasphere2 : DRPGMegasphere
{
	States
	{
	Pickup:
		TNT1 A 0 A_GiveInventory("RLSoulSphere4")
		TNT1 A 0 ACS_NamedExecuteAlways("AddEP", 0, 1000000)
		TNT1 A 0 ACS_NamedExecuteAlways("AddShield", 0, 1000000)
        TNT1 A 0 ACS_NamedExecuteAlways("AddMedkit", 0, 1000000)
		TNT1 A 0 A_JumpIfInventory ("RLIndestructibleArmorWorn", 1, "NoRepair")
		TNT1 A 0 A_JumpIfInventory ("BasicArmor", 1, 2)
		Stop
	NoRepair:
        TNT1 A 0 A_JumpIfInventory ("RLDemonicSetBonusActive", 1, "DemonicCharge")
		Stop
		TNT1 A 0 A_JumpIfInventory ("RL100ArmorWorn", 1, "100Armor")
		TNT1 A 0 A_JumpIfInventory ("RL150ArmorWorn", 1, "150Armor")
		TNT1 A 0 A_JumpIfInventory ("RL200ArmorWorn", 1, "200Armor")
		TNT1 A 0 A_JumpIfInventory ("RL100RegenArmorWorn", 1, "100Armor")
        stop
	100Armor:
		TNT1 A 0 A_GiveInventory("RLArmorBonus100Megasphere", 1)
    TNT1 A 0 A_JumpIfInventory ("RLDemonicSetBonusActive", 1, "DemonicCharge")
		Stop
	150Armor:
		TNT1 A 0 A_GiveInventory("RLArmorBonus150Megasphere", 1)
    TNT1 A 0 A_JumpIfInventory ("RLDemonicSetBonusActive", 1, "DemonicCharge")
		Stop
	200Armor:
		TNT1 A 0 A_GiveInventory("RLArmorBonus200Megasphere", 1)
    TNT1 A 0 A_JumpIfInventory ("RLDemonicSetBonusActive", 1, "DemonicCharge")
		Stop
    DemonicCharge:
        TNT1 A 0 A_GiveInventory ("RLDemonicCarapaceSupercharge", 1)
        TNT1 A 0 A_Print("Demonic Carapace supercharged!")
        TNT1 A 0
        Stop
	}
}

ACTOR PowerRLLavaSetBonusInvulnerable2 : PowerInvulnerable Replaces PowerRLLavaSetBonusInvulnerable
{
	Powerup.Duration -9
	inventory.icon ""
	Powerup.Color GoldMap
}

**Comment by doomsguy214** [comment]
downloading working one from here
https://github.com/Kyle873/DoomRPG/archive/86c6ba36d081a3c8228f812374b53cb735c2e53c.zip

**Comment by Cassidaygloves** [comment]
In using that version that was linked above, when ever you try to bring up the arsenal recipes, it comes up in a tiny box and then trying to change the page, the game immediately crashes.

**Comment by Sumwunn** [comment]
I was having a ton of little issues like that including my entire save crapping out due to crashing scripts.

It seems using the latest DoomRPG.lib from here (dated March) has fixed all issues for me so far.

**Comment by doomsguy214** [comment]
Can you give me link to DoomRPG.lib from here (dated March) If Possible

**Comment by marrub--** [comment]
Quit commenting on this issue, it keeps pinging a bot on our server. :smile:
